//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LuaStudio.rc
//
#define IDR_MAINFRAME                   128
#define IDR_LUA_SRC_TYPE                129
#define IDR_LUA_CODE_TYPE               130
#define IDD_ASSEMBLE                    133
#define IDD_PROPPAGE_EDITOR             140
#define IDD_EDIT_BREAKPOINT             144
#define IDR_POPUP_EDIT                  147
#define IDD_PROPPAGE_GENERAL            148
#define IDR_POPUP_MEMORY                148
#define IDR_POPUP_ZPMEMORY              149
#define IDR_IDENT_INFO                  150
#define IDR_POPUP_TERMINAL              150
#define IDI_MEMORY_INFO                 151
#define IDI_ARROW                       153
#define IDI_IO_WINDOW                   157
#define IDD_PROPPAGE_VIEW               165
#define IDB_CODE                        168
#define IDB_DEBUG                       169
#define IDB_ABOUT                       175
#define IDC_LINK                        176
#define IDC_LINK_LUA                    177
#define IDR_ACCELERATOR1                178
#define IDD_ABOUTBOX                    1000
#define IDB_CLOSE_TB                    1001
#define IDD_REGISTERBARX                1004
#define IDD_REGISTERBAR                 1005
#define IDR_POPUP_DEASM6502             1009
#define IDC_ZPG_BAR_EDIT                1011
#define IDC_OPT_DA_INSTR_COL            1015
#define IDC_ASM_PROGRESS                1016
#define IDC_PASS_NO                     1017
#define IDC_DIAL_ASM_ERR                1018
#define IDC_CURR_ROW                    1019
#define IDC_REGS_A                      1020
#define IDC_REGS_X                      1021
#define IDC_REGS_Y                      1022
#define IDC_REGS_S                      1023
#define IDC_REGS_P                      1024
#define IDC_REGS_PC                     1025
#define IDC_REGS_A_MEM                  1026
#define IDC_REGS_X_MEM                  1027
#define IDC_REGS_Y_MEM                  1028
#define IDC_REGS_S_MEM                  1029
#define IDC_REGS_INSTR                  1030
#define IDC_REGS_NEG                    1031
#define IDC_REGS_ZERO                   1032
#define IDC_REGS_OVER                   1033
#define IDC_REGS_CARRY                  1034
#define IDC_REGS_INT                    1035
#define IDC_REGS_BRK                    1036
#define IDC_REGS_DEC                    1037
#define IDC_REGS_INSTR_ARG              1038
#define IDC_REGS_STAT                   1039
#define IDC_REGS_CYCLES_CLR             1040
#define IDC_REGS_CYCLES                 1041
#define IDS_REGS_S_EMPTY                1042
#define IDS_OPT_VIEW_EXAMPLE            1200
#define IDS_OPT_VIEW_EXAMPLE_1          1201
#define IDS_OPT_VIEW_EXAMPLE_2          1202
#define IDS_OPT_VIEW_EXAMPLE_3          1203
#define IDS_OPT_VIEW_EXAMPLE_4          1204
#define IDS_OPT_VIEW_EXAMPLE_5          1205
#define IDS_OPT_VIEW_EXAMPLE_6          1206
#define IDS_OPT_VIEW_LIST               1207
#define IDS_SYM_STAT_OK                 1312
#define IDS_SYM_STAT_BPX                1313
#define IDS_SYM_STAT_BPR                1314
#define IDS_SYM_STAT_BPW                1315
#define IDS_SYM_STAT_ILL                1316
#define IDS_SYM_STAT_RUN                1317
#define IDS_SYM_STAT_INP_WAIT           1318
#define IDS_SYM_ILL_WRITE               1319
#define IDC_EDIT_BP_DISABLED            1345
#define IDC_EDIT_BP_EXEC                1366
#define IDC_EDIT_BP_READ                1367
#define IDC_EDIT_BP_WRITE               1368
#define IDC_DIAL_ASM_ICN1               1374
#define IDC_DIAL_ASM_ICN2               1375
#define IDC_DIAL_ASM_ICN3               1376
#define IDC_ABOUT_VER                   1426
#define IDS_ERR_ASM_THREAD              1446
#define IDS_DIAL_ASM_OK                 1447
#define IDS_ROW_COLUMN                  1448
#define IDS_ERR_SYM_THREAD              1449
#define IDS_ASM_FORM1                   1456
#define IDS_ASM_FORM2                   1457
#define IDS_ASM_FORM3                   1458
#define IDS_ASM_FORM4                   1459
#define IDS_ASM_FORM5                   1460
#define IDS_ASM_FORM6                   1461
#define IDS_ASM_ERR_MSG_FIRST           1462
#define IDS_ASM_ERR_01                  1463
#define IDS_ASM_ERR_02                  1464
#define IDS_ASM_ERR_03                  1465
#define IDS_ASM_ERR_04                  1466
#define IDS_ASM_ERR_05                  1467
#define IDS_ASM_ERR_06                  1468
#define IDS_ASM_ERR_07                  1469
#define IDS_ASM_ERR_08                  1470
#define IDS_ASM_ERR_09                  1471
#define IDS_ASM_ERR_10                  1472
#define IDS_ASM_ERR_11                  1473
#define IDS_ASM_ERR_12                  1474
#define IDS_ASM_ERR_13                  1475
#define IDS_ASM_ERR_14                  1476
#define IDS_ASM_ERR_15                  1477
#define IDS_ASM_ERR_16                  1478
#define IDS_ASM_ERR_17                  1479
#define IDS_ASM_ERR_18                  1480
#define IDS_ASM_ERR_19                  1481
#define IDS_ASM_ERR_20                  1482
#define IDS_ASM_ERR_21                  1483
#define IDS_ASM_ERR_22                  1484
#define IDS_ASM_ERR_23                  1485
#define IDS_ASM_ERR_24                  1486
#define IDS_ASM_ERR_25                  1487
#define IDS_ASM_ERR_26                  1488
#define IDS_ASM_ERR_27                  1489
#define IDS_ASM_ERR_28                  1490
#define IDS_ASM_ERR_29                  1491
#define IDS_ASM_ERR_30                  1492
#define IDS_ASM_ERR_31                  1493
#define IDS_ASM_ERR_32                  1494
#define IDS_ASM_ERR_33                  1495
#define IDS_ASM_ERR_34                  1496
#define IDS_ASM_ERR_35                  1497
#define IDS_ASM_ERR_36                  1498
#define IDS_ASM_ERR_37                  1499
#define IDS_ASM_ERR_38                  1500
#define IDS_ASM_ERR_39                  1501
#define IDS_ASM_ERR_40                  1502
#define IDS_ASM_ERR_41                  1503
#define IDS_ASM_ERR_42                  1504
#define IDS_ASM_ERR_43                  1505
#define IDS_ASM_ERR_44                  1506
#define IDS_ASM_ERR_45                  1507
#define IDS_ASM_ERR_46                  1508
#define IDS_ASM_ERR_47                  1509
#define IDS_ASM_ERR_48                  1510
#define IDS_ASM_ERR_49                  1511
#define IDS_ASM_ERR_50                  1512
#define IDS_ASM_ERR_51                  1513
#define IDS_ASM_ERR_52                  1514
#define IDS_ASM_ERR_53                  1515
#define IDS_ASM_ERR_54                  1516
#define IDS_ASM_ERR_55                  1517
#define IDS_ASM_ERR_56                  1518
#define IDS_ASM_ERR_57                  1519
#define IDS_ASM_ERR_58                  1520
#define IDS_ASM_ERR_59                  1521
#define IDS_ASM_ERR_60                  1522
#define IDS_SRC_NO_CODE                 1534
#define IDS_SYM_STAT_STOP               1535
#define IDS_SYM_STAT_FIN                1536
#define IDS_OPTIONS                     1537
#define IDS_SRC_NO_CODE2                1538
#define IDS_SRC_NO_CODE3                1539
#define IDS_SRC_DATA                    1540
#define IDS_MAINFRM_PROG_RUNNING        1541
#define IDS_MSG_HEX_STR                 1542
#define IDS_IDENT_TITLE                 1543
#define IDS_IDENT_COL_NAME              1544
#define IDS_IDENT_COL_VALUE             1545
#define IDS_IDENT_COL_AREA              1546
#define IDS_IDENT_GLOBAL                1547
#define IDS_MEMORY_TITLE                1548
#define IDS_IO_WINDOW                   1549
#define IDS_SAVE_CODE                   1550
#define IDS_MSG_BAD_DEC_HEX_NUM         1551
#define IDS_SAVE_CODE_ERR_1             1552
#define IDS_SAVE_CODE_ERR_2             1553
#define IDS_LOAD_CODE                   1554
#define IDS_LOAD_CODE_ERR_1             1555
#define IDS_LOAD_CODE_ERR_2             1556
#define IDS_LOAD_CODE_DLG               1557
#define IDS_SAVE_CODE_DLG               1558
#define IDS_INTEL_HEX_ERR_1             1559
#define IDS_INTEL_HEX_ERR_2             1560
#define IDS_INTEL_HEX_ERR_3             1561
#define IDS_INTEL_HEX_ERR_4             1562
#define IDS_CODE_EXTENSIONS             1563
#define IDS_STOP_DEBUG                  1564
#define IDS_ASM_OPT_LIST_FILES          1565
#define IDS_MOTOROLA_S_ERR_1            1566
#define IDS_MOTOROLA_S_ERR_2            1567
#define IDS_MOTOROLA_S_ERR_3            1568
#define IDS_MOTOROLA_S_ERR_4            1569
#define IDS_ZMEMORY_TITLE               1570
#define IDS_ABOUT_VER                   1578
#define IDS_STACK                       1580
#define IDC_ADDR                        2103
#define IDC_OPT_ED_EXAMPLE              2111
#define IDC_OPT_ED_ELEMENT              2112
#define IDC_OPT_ED_BOLD_FONT            2113
#define IDC_OPT_ED_COLOR                2114
#define IDC_TITLE                       2115
#define IDC_OPT_ED_AUTO_SYNTAX          2303
#define IDC_OPT_ED_AUTO_UPPER_CASE      2306
#define IDC_OPT_ED_NEW_FILE             2307
#define IDC_OPT_BUS_SPIN                2308
#define IDC_OPT_BUS_WIDTH               2309
#define IDC_OPT_ED_FONT_BTN             2310
#define IDC_OPT_ED_FONT_NAME            2312
#define IDC_OPT_ED_TAB_STEP             2314
#define IDC_OPT_SYM_FONT_BTN            2315
#define IDC_OPT_ED_AUTO_INDENT          2316
#define IDC_OPT_SYM_FONT_NAME           2317
#define IDC_OPT_ED_COLOR_SYNTAX         2317
#define IDC_OPT_ED_TAB_SPIN             2320
#define IDC_OPT_MARK_PTR_COL            2322
#define IDC_OPT_MARK_BRKP_COL           2323
#define IDC_OPT_MARK_ERR_COL            2324
#define IDC_OPT_SYM_WND_TXT_COL         2327
#define IDC_OPT_SYM_WND_BGND_COL        2328
#define IDC_OPT_VIEW_BKGND_COL          2329
#define IDC_OPT_6502                    2330
#define IDC_OPT_65C02                   2331
#define IDC_OPT_FONT_BTN                2338
#define IDC_OPT_FONT_NAME               2339
#define IDC_OPT_VIEW_WND                2340
#define IDC_OPT_VIEW_TXT_COL            2341
#define IDC_OPT_VIEW_EXAMPLE            2342
#define IDC_OPT_VIEW_FONT_BTN           2343
#define IDC_OPT_VIEW_FONT_NAME          2344
#define ID_FILE_SAVE_CODE               2400
#define ID_FILE_OPEN_CODE               2401
#define ID_SIM_DEBUG                    2500
#define ID_SIM_GO                       2501
#define ID_SIM_STEP_INTO                2502
#define ID_SIM_ASSEMBLE                 2503
#define ID_SIM_OPTIONS                  2504
#define ID_SIM_STEP_OVER                2505
#define ID_SIM_GO_RTS                   2506
#define ID_SIM_GO_LINE                  2507
#define ID_SIM_DEBUG_STOP               2508
#define ID_SIM_BREAKPOINT               2509
#define ID_SIM_GEN_IRQ                  2510
#define ID_SIM_GEN_NMI                  2511
#define ID_SIM_GEN_RST                  2512
#define ID_SIM_GEN_INT                  2513
#define ID_SIM_SKIP_INSTR               2514
#define ID_SIM_SKIP_TO_LINE             2515
#define ID_SIM_BREAK                    2516
#define ID_SIM_RESTART                  2517
#define ID_SIM_EDIT_BREAKPOINT          2518
#define ID_SIM_GO_TO_CURSOR             2519
#define ID_EDITOR_OPT                   2600
#define ID_VIEW_DEASM                   2700
#define ID_VIEW_IDENT                   2701
#define ID_VIEW_MEMORY                  2702
#define ID_VIEW_IO_WINDOW               2703
#define ID_VIEW_LOCAL_VARS              2704
#define ID_DEASM_GOTO                   2800
#define ID_DEASM_OPTIONS                2801
#define ID_MEMORY_GOTO                  2900
#define ID_MEMORY_OPTIONS               2901
#define ID_MEMORY_CHG                   2902
#define ID_MEMORY_FULL                  2903
#define ID_MEMORY_HEX                   2904
#define ID_MEMORY_TEXT                  2905
#define IDS_TOOLBAR                     3000
#define ID_VIEW_STACK                   3003
#define ID_VIEW_LOG                     3006
#define IDS_DISASM_FORMAT1              3008
#define IDS_DISASM_FORMAT2              3009
#define ID_PASTE                        3010
#define ID_HELP_DYNAMIC                 3011
#define ID_ACCELERATOR3012              3012
#define ID_SIM_STEP_OUT                 3012
#define ID_ACCELERATOR3015              3015
#define ID_VIEW_GLOBAL_VARS             3015
#define ID_EDIT_VIEW_TABS               8600
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define IDC_EDIT_WHOLE_WORD             8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDC_EDIT_TEXT                   8605
#define IDS_EDIT_TEXT_NOT_FOUND         8606
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDR_DEFAULT_ACCEL               22901
#define IDR_MARGIN_ICONS                22902
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_DELETE_TO_EOL           37006
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226
#define ID_EDIT_TOGGLE_BLOCK            37300
#define ID_EDIT_COLLAPSE_ALL            37301
#define ID_EDIT_EXPAND_ALL              37302
#define ID_VIEW_REGISTERBAR             37303
#define ID_EDIT_INDICATOR_POSITION      37903
#define IDS_DYNAMIC_HELP                37904
#define ID_VIEW_ZEROPAGEBAR             0xE805

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         3017
#define _APS_NEXT_CONTROL_VALUE         2116
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
